### ISSUE TITLE
Generating use cases and review other specs

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-webperf#20]
One additional comment we should consider:
[[
Doesn't need to be in the Charter, but the WG could consider generating ideas for performance related specs and, where it directly impacts a particular WG, suggest the other WG own the spec. So, in addition to creating specs itself, it could serve a cross group role of suggesting performance improvements in other WGs.
]]

**Comment by toddreifsteck** [comment]
Could the source of this comment be provided to assist with context?

**Comment by plehegar** [comment]
Not directly since the source isn't public but happy to give more context separately.

**Comment by igrigorik** [comment]
> Other non-normative documents may be created such as:
> ...
> Use cases documents to support development and exploration of performance-critical web platform features and APIs;

Do we need to extend above language?

**Comment by wayneca** [comment]
This issue came out of a comment I made in the current AC Review of the Charter.  It wasn't about use cases - rather the Charter could say the performance WG also acts as a horizontal group, making performance suggestions to other groups, including suggesting work for other groups rather than only doing specs in the performance WG itself.   (so like privacy, security, I18N, accessibility).  e.g. the performance WG could identify a needed performance spec and WebApps could do it.

**Comment by plehegar** [comment]
See proposed wording in the pull request

**Comment by toddreifsteck** [comment]
Pull request is merged. Closing issue.
